#!/usr/bin/env bash
# Unified EDF adoption orchestration wrapper.
#
# Usage:
#   ./scripts/adopt-edf.sh bootstrap [--profile core|software-engineering] "/path/to/project"
#   ./scripts/adopt-edf.sh migrate "/path/to/project"
#   ./scripts/adopt-edf.sh validate "/path/to/project"
#
# Compatible with Bash 3.2+.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
    echo "Usage: $(basename "$0") <bootstrap|migrate|validate> [--profile core|software-engineering] \"/path/to/project root\"" >&2
    exit 1
}

COMMAND=""
PROFILE=""
PROJECT_ROOT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        bootstrap|migrate|validate)
            COMMAND="$1"
            shift
            ;;
        --profile)
            PROFILE="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            if [[ -z "$PROJECT_ROOT" ]]; then
                PROJECT_ROOT="${1%/}"
            else
                echo "Error: unexpected argument: $1" >&2
                usage
            fi
            shift
            ;;
    esac
done

[[ -n "$COMMAND" ]] || usage
[[ -n "$PROJECT_ROOT" ]] || usage

if [[ ! -d "$PROJECT_ROOT" ]]; then
    echo "Error: project root does not exist or is not a directory: $PROJECT_ROOT" >&2
    exit 1
fi

profile_args=()
if [[ -n "$PROFILE" ]]; then
    profile_args=(--profile "$PROFILE")
fi

run_script() {
    local script_path="$1"
    shift

    if [[ ! -f "$script_path" ]]; then
        echo "Error: required script not found: $script_path" >&2
        exit 1
    fi

    /bin/bash "$script_path" "$@"
}

write_adoption_config_if_needed() {
    local config_file="$PROJECT_ROOT/edf-adoption.yaml"

    if [[ -n "$PROFILE" && ! -f "$config_file" ]]; then
        cat >"$config_file" <<EOF
# Generated by adopt-edf.sh bootstrap
profile: $PROFILE
project_name: $(basename "$PROJECT_ROOT")
copy_ai_handbook: false
EOF
        echo "Created: edf-adoption.yaml (profile: $PROFILE)"
        echo
    fi
}

case "$COMMAND" in
    bootstrap)
        echo "EDF bootstrap: $PROJECT_ROOT"
        echo "================================"
        echo
        run_script "$script_dir/create_canonical_structure.sh" "${profile_args[@]}" "$PROJECT_ROOT"
        echo
        write_adoption_config_if_needed
        run_script "$script_dir/generate_documentation_skeleton.sh" "$PROJECT_ROOT"
        echo
        echo "Running conformance validation..."
        run_script "$script_dir/run_conformance_validation.sh" "$PROJECT_ROOT"
        echo
        echo "Bootstrap complete. Next steps:"
        echo "- Customize PROJECT_CHARTER.md and PROJECT_INDEX.md"
        echo "- Copy docs/Templates/ADOPTION_STATUS_Template.md to ADOPTION_STATUS.md"
        echo "- See docs/Development/Bootstrap_Guide.md"
        ;;
    migrate)
        echo "EDF migration planning: $PROJECT_ROOT"
        echo "===================================="
        echo
        run_script "$script_dir/analyze_project_structure.sh" "$PROJECT_ROOT"
        echo
        run_script "$script_dir/plan_documentation_migration.sh" \
            --output "$PROJECT_ROOT/MIGRATION_PLAN.md" \
            "$PROJECT_ROOT"
        echo
        echo "Migration planning complete."
        echo "- Review $PROJECT_ROOT/MIGRATION_PLAN.md"
        echo "- See docs/Development/Migration_Guide.md"
        ;;
    validate)
        run_script "$script_dir/run_conformance_validation.sh" "$PROJECT_ROOT"
        ;;
esac
