<#
Unified EDF adoption orchestration wrapper.

Usage:
  .\scripts\adopt-edf.ps1 -Command bootstrap -ProjectRoot "D:\Projects\My Project"
  .\scripts\adopt-edf.ps1 -Command bootstrap -Profile core -ProjectRoot "D:\Projects\My Project"
  .\scripts\adopt-edf.ps1 -Command migrate -ProjectRoot "D:\Projects\My Project"
  .\scripts\adopt-edf.ps1 -Command validate -ProjectRoot "D:\Projects\My Project"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("bootstrap", "migrate", "validate")]
    [string] $Command,

    [Parameter(Mandatory = $true)]
    [string] $ProjectRoot,

    [ValidateSet("core", "software-engineering")]
    [string] $Profile = ""
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

if (-not (Test-Path -LiteralPath $ProjectRoot -PathType Container)) {
    Write-Error "Project root does not exist or is not a directory: $ProjectRoot"
}

function Invoke-EdfScript {
    param(
        [string] $ScriptName,
        [object[]] $Arguments = @()
    )

    $scriptPath = Join-Path -Path $scriptDir -ChildPath $ScriptName
    if (-not (Test-Path -LiteralPath $scriptPath -PathType Leaf)) {
        throw "Required script not found: $scriptPath"
    }

    & $scriptPath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Script failed: $ScriptName (exit $LASTEXITCODE)"
    }
}

switch ($Command) {
    "bootstrap" {
        Write-Host "EDF bootstrap: $ProjectRoot"
        Write-Host "================================"
        Write-Host ""

        $structureArgs = @("-ProjectRoot", $ProjectRoot)
        if ($Profile) {
            $structureArgs += @("-Profile", $Profile)
        }

        Invoke-EdfScript -ScriptName "create_canonical_structure.ps1" -Arguments $structureArgs
        Write-Host ""

        $configFile = Join-Path -Path $ProjectRoot -ChildPath "edf-adoption.yaml"
        if ($Profile -and -not (Test-Path -LiteralPath $configFile -PathType Leaf)) {
            $projectName = Split-Path -Path $ProjectRoot -Leaf
            @(
                "# Generated by adopt-edf.ps1 bootstrap",
                "profile: $Profile",
                "project_name: $projectName",
                "copy_ai_handbook: false"
            ) | Set-Content -LiteralPath $configFile -Encoding UTF8
            Write-Host "Created: edf-adoption.yaml (profile: $Profile)"
            Write-Host ""
        }

        Invoke-EdfScript -ScriptName "generate_documentation_skeleton.ps1" -Arguments @("-ProjectRoot", $ProjectRoot)
        Write-Host ""
        Write-Host "Running conformance validation..."
        Invoke-EdfScript -ScriptName "run_conformance_validation.ps1" -Arguments @("-ProjectRoot", $ProjectRoot)
        Write-Host ""
        Write-Host "Bootstrap complete. Next steps:"
        Write-Host "- Customize PROJECT_CHARTER.md and PROJECT_INDEX.md"
        Write-Host "- Copy docs/Templates/ADOPTION_STATUS_Template.md to ADOPTION_STATUS.md"
        Write-Host "- See docs/Development/Bootstrap_Guide.md"
    }
    "migrate" {
        Write-Host "EDF migration planning: $ProjectRoot"
        Write-Host "===================================="
        Write-Host ""

        Invoke-EdfScript -ScriptName "analyze_project_structure.ps1" -Arguments @("-ProjectRoot", $ProjectRoot)
        Write-Host ""

        $migrationPlan = Join-Path -Path $ProjectRoot -ChildPath "MIGRATION_PLAN.md"
        Invoke-EdfScript -ScriptName "plan_documentation_migration.ps1" -Arguments @(
            "-ProjectRoot", $ProjectRoot,
            "-OutputFile", $migrationPlan
        )
        Write-Host ""
        Write-Host "Migration planning complete."
        Write-Host "- Review $migrationPlan"
        Write-Host "- See docs/Development/Migration_Guide.md"
    }
    "validate" {
        Invoke-EdfScript -ScriptName "run_conformance_validation.ps1" -Arguments @("-ProjectRoot", $ProjectRoot)
    }
}
