# These scripts only create missing directories and the optional framework guide file.
# They do not delete, overwrite, move, rename, or modify existing files.
#
# Usage:
# .\scripts\create_canonical_structure.ps1 -ProjectRoot "D:\Projects\Existing Project"

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string] $ProjectRoot
)

$ErrorActionPreference = "Stop"
$GuideFileName = "ENGINEERING_DOCUMENTATION_FRAMEWORK.md"

if (-not (Test-Path -LiteralPath $ProjectRoot -PathType Container)) {
    Write-Error "Project root does not exist or is not a directory: $ProjectRoot"
}

$dirs = @(
    "docs/Architecture",
    "docs/Architecture/ADRs",
    "docs/AI",
    "docs/Development",
    "docs/Specifications",
    "docs/API",
    "docs/Database",
    "docs/Deployment",
    "docs/User_Guides",
    "docs/Reference",
    "docs/Templates",
    "tasks",
    "archive",
    "scripts"
)

function Get-FrameworkGuideContent {
@'
# Engineering Documentation Framework

This project has adopted the **Engineering Documentation Framework** for organizing engineering documentation in a consistent, scalable, and AI-friendly structure.

## Documentation Root

**`docs/`** is the canonical documentation root for this project. Authoritative engineering documentation should live under `docs/` unless explicitly noted otherwise.

## Primary Documentation Entry Point

`PROJECT_INDEX.md` should be the primary navigation hub for both humans and AI assistants. The project root `README.md` should link to it.

## Legacy Content

**`documents/`** is treated as legacy or project-specific content. Framework bootstrap scripts do **not** create, modify, move, or remove anything under `documents/`.

Migrate content into the appropriate `docs/` domain over time, or leave it in place if it serves a distinct purpose.

## Project Areas

| Path | Purpose |
|---|---|
| `tasks/` | Task planning and implementation tracking |
| `archive/` | Obsolete or superseded documentation |
| `scripts/` | Project utility scripts |

## Documentation Domains

| Path | Purpose |
|---|---|
| `docs/Architecture/` | System architecture and documentation architecture |
| `docs/Architecture/ADRs/` | Individual Architecture Decision Records |
| `docs/AI/` | Modular AI Engineering Handbook |
| `docs/Development/` | Developer workflow, coding practices, and engineering tools |
| `docs/Specifications/` | Requirements and feature specifications |
| `docs/API/` | API contracts and interface documentation |
| `docs/Database/` | Schema and persistence design |
| `docs/Deployment/` | Deployment, operations, and runbooks |
| `docs/User_Guides/` | End-user documentation |
| `docs/Reference/` | Glossary, standards, terminology, and external references |
| `docs/Templates/` | Reusable documentation templates |

## AI Engineering Handbook

The authoritative AI documentation entry point is:

`docs/AI/README.md`

The AI handbook may include:

- `AI_Philosophy.md`
- `AI_Roles.md`
- `AI_Decision_Matrix.md`
- `Cost_Optimization.md`
- `Prompting_Guide.md`
- `Context_Checklist.md`
- `Verification.md`
- `Security.md`
- `Governance.md`

A root-level `AI_WORKFLOW.md` is considered a legacy monolithic document. Migrate any unique content into the modular AI handbook and remove the root file only after verifying that no information or links are lost.

## Next Steps

1. Add or customize `PROJECT_INDEX.md`, `PROJECT_CHARTER.md`, and other root navigation documents.
2. Point the root `README.md` to `PROJECT_INDEX.md`.
3. Audit existing documentation and map it to the appropriate domains.
4. Migrate content incrementally.
5. Use framework templates for new documents.
6. Run the analysis and migration scripts after major documentation changes.

---

_This file was generated by the Engineering Documentation Framework bootstrap scripts. Customize it for this project._
'@
}

function New-DirectoryIfMissing {
    param([string] $RelativePath)

    $fullPath = Join-Path -Path $ProjectRoot -ChildPath $RelativePath

    if (Test-Path -LiteralPath $fullPath -PathType Container) {
        Write-Host "Exists: $RelativePath"
    }
    elseif (Test-Path -LiteralPath $fullPath) {
        Write-Warning "Skipped: $RelativePath (path exists but is not a directory)"
        return $false
    }
    else {
        New-Item -ItemType Directory -LiteralPath $fullPath | Out-Null
        Write-Host "Created: $RelativePath"
    }

    return $true
}

function New-FrameworkGuideIfMissing {
    $guidePath = Join-Path -Path $ProjectRoot -ChildPath $GuideFileName

    if (Test-Path -LiteralPath $guidePath -PathType Leaf) {
        Write-Host "Exists: $GuideFileName"
        return $true
    }
    elseif (Test-Path -LiteralPath $guidePath) {
        Write-Warning "Skipped: $GuideFileName (path exists but is not a file)"
        return $false
    }

    [System.IO.File]::WriteAllText($guidePath, (Get-FrameworkGuideContent))
    Write-Host "Created: $GuideFileName"
    return $true
}

Write-Host "Ensuring canonical folder structure under: $ProjectRoot"
Write-Host ""

$documentsPath = Join-Path -Path $ProjectRoot -ChildPath "documents"
if (Test-Path -LiteralPath $documentsPath -PathType Container) {
    Write-Host "Leaving documents/ untouched."
    Write-Host ""
}

$errors = 0

foreach ($dir in $dirs) {
    if (-not (New-DirectoryIfMissing -RelativePath $dir)) {
        $errors++
    }
}

Write-Host ""

if (-not (New-FrameworkGuideIfMissing)) {
    $errors++
}

Write-Host ""

if ($errors -gt 0) {
    Write-Warning "Finished with $errors skipped path(s)."
    exit 1
}

Write-Host "Done."
