# These scripts only create missing directories and the optional framework guide file.
# They do not delete, overwrite, move, rename, or modify existing files.
#
# Creates the canonical Engineering Documentation Framework folder layout inside an
# existing software project's root directory.
# Safe to run repeatedly — existing directories and files are left unchanged.
# The legacy documents/ folder is never created, modified, or removed.
#
# Usage:
#   .\scripts\create_canonical_structure.ps1 -ProjectRoot "D:\Projects\The Recipe Vault"
#
# Example:
#   .\scripts\create_canonical_structure.ps1 -ProjectRoot "D:\Projects\The Recipe Vault"

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string] $ProjectRoot
)

$ErrorActionPreference = "Stop"

$GuideFileName = "ENGINEERING_DOCUMENTATION_FRAMEWORK.md"

if (-not (Test-Path -LiteralPath $ProjectRoot -PathType Container)) {
    Write-Error "Project root does not exist or is not a directory: $ProjectRoot"
}

# Canonical folder structure (relative to project root).
# Note: documents/ is intentionally excluded — legacy content must remain untouched.
$dirs = @(
    "docs/Architecture",
    "docs/Architecture/ADRs",
    "docs/AI",
    "docs/Development",
    "docs/Specifications",
    "docs/API",
    "docs/Database",
    "docs/Deployment",
    "docs/User_Guides",
    "docs/Reference",
    "docs/Templates",
    "tasks",
    "archive",
    "scripts"
)

function Get-FrameworkGuideContent {
    @'
# Engineering Documentation Framework

This project has adopted the **Engineering Documentation Framework** for organizing engineering documentation in a consistent, scalable, and AI-friendly structure.

## Documentation root

**`docs/`** is the canonical documentation root for this project. Authoritative engineering documentation should live under `docs/` unless explicitly noted otherwise.

## Legacy content

**`documents/`** is treated as legacy or project-specific content. Framework bootstrap scripts do **not** create, modify, move, or remove anything under `documents/`. Migrate content into the appropriate `docs/` domain over time, or leave it in place if it serves a distinct purpose.

## Project areas

| Path | Purpose |
|------|---------|
| `tasks/` | Task planning and implementation tracking |
| `archive/` | Obsolete or superseded documentation |
| `scripts/` | Project utility scripts |

## Documentation domains

| Path | Purpose |
|------|---------|
| `docs/Architecture/` | System architecture and ADRs |
| `docs/Architecture/ADRs/` | Individual Architecture Decision Records |
| `docs/AI/` | AI workflow and AI engineering guidance |
| `docs/Development/` | Developer workflow and coding practices |
| `docs/Specifications/` | Requirements and feature specifications |
| `docs/API/` | API contracts |
| `docs/Database/` | Schema and persistence design |
| `docs/Deployment/` | Deployment and operations |
| `docs/User_Guides/` | End-user documentation |
| `docs/Reference/` | Glossary, standards, terminology, and external references |
| `docs/Templates/` | Reusable documentation templates |

## Next steps

1. Add or copy framework navigation documents (for example `PROJECT_INDEX.md`, `PROJECT_CHARTER.md`) if not already present.
2. Map existing documentation to the domains above.
3. Use `PROJECT_INDEX.md` as the living navigation hub once established.

---

_This file was generated by the Engineering Documentation Framework bootstrap scripts. Customize it for this project._
'@
}

function New-DirectoryIfMissing {
    param(
        [string] $RelativePath
    )

    $fullPath = Join-Path -Path $ProjectRoot -ChildPath $RelativePath

    if (Test-Path -LiteralPath $fullPath -PathType Container) {
        Write-Host "Exists:  $RelativePath"
    }
    elseif (Test-Path -LiteralPath $fullPath) {
        Write-Warning "Skipped: $RelativePath (path exists but is not a directory)"
        return $false
    }
    else {
        New-Item -ItemType Directory -LiteralPath $fullPath | Out-Null
        Write-Host "Created: $RelativePath"
    }

    return $true
}

function New-FrameworkGuideIfMissing {
    $guidePath = Join-Path -Path $ProjectRoot -ChildPath $GuideFileName

    if (Test-Path -LiteralPath $guidePath -PathType Leaf) {
        Write-Host "Exists:  $GuideFileName"
        return $true
    }
    elseif (Test-Path -LiteralPath $guidePath) {
        Write-Warning "Skipped: $GuideFileName (path exists but is not a file)"
        return $false
    }

    $content = Get-FrameworkGuideContent
    [System.IO.File]::WriteAllText($guidePath, $content)
    Write-Host "Created: $GuideFileName"
    return $true
}

Write-Host "Ensuring canonical folder structure under: $ProjectRoot"
Write-Host ""

$documentsPath = Join-Path -Path $ProjectRoot -ChildPath "documents"
if (Test-Path -LiteralPath $documentsPath -PathType Container) {
    Write-Host "Leaving documents/ untouched."
    Write-Host ""
}

$errors = 0
foreach ($dir in $dirs) {
    if (-not (New-DirectoryIfMissing -RelativePath $dir)) {
        $errors++
    }
}

Write-Host ""
if (-not (New-FrameworkGuideIfMissing)) {
    $errors++
}

Write-Host ""
if ($errors -gt 0) {
    Write-Warning "Finished with $errors skipped path(s)."
    exit 1
}

Write-Host "Done."
